server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, ASMAS
        - AddRequestHeader=X-Environment, QA

      routes:

        # AUTH - PUBLIC
        - id: auth-service
          uri: http://ec2-54-92-195-3.compute-1.amazonaws.com:8081
          predicates:
            - Path=/auth/**

        # # PROTECTED SERVICES---
        # - id: survey-command
        #   uri: http://<QA_COMMAND_DNS>:8083
        #   predicates:
        #     - Path=/protected/**
        #   filters:
        #     - name: JwtAuthenticationFilter

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: asmas-qa-secret-key-256-bits-minimum-length-123456
  expiration: 3600000
